#!/usr/bin/env node
/**
 * Catalog Script — regenerates COMPONENT_LEVEL_MAP and components/catalog.ts
 *
 * Scans components/atoms/, molecules/, organisms/ for existing component folders
 * and updates the componentTokenParser.ts map and catalog.ts in one pass.
 *
 * Usage:
 *   npx tsx scripts/catalog.ts
 *
 * Safety: reads before writing, shows diff summary, never deletes entries.
 */

import fs from 'fs/promises'
import path from 'path'

const ROOT = path.resolve(__dirname, '../..')
const COMPONENTS_DIR = path.join(ROOT, 'components')
const PARSER_FILE = path.join(ROOT, 'app/src/utils/componentTokenParser.ts')
const CATALOG_FILE = path.join(ROOT, 'components/catalog.ts')

const TIERS = [
  { name: 'atoms', level: 'atom' },
  { name: 'molecules', level: 'molecule' },
  { name: 'organisms', level: 'organism' },
]

interface ComponentInfo {
  name: string
  level: string
  folder: string
}

async function scanComponents(): Promise<ComponentInfo[]> {
  const result: ComponentInfo[] = []

  for (const { name, level } of TIERS) {
    const tierDir = path.join(COMPONENTS_DIR, name)
    try {
      const entries = await fs.readdir(tierDir, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.isDirectory()) {
          const tsxPath = path.join(tierDir, entry.name, `${entry.name}.tsx`)
          try {
            await fs.access(tsxPath)
            result.push({ name: entry.name, level, folder: path.join(name, entry.name) })
          } catch {
            // No TSX file — skip
          }
        }
      }
    } catch {
      // Tier folder doesn't exist
    }
  }

  return result.sort((a, b) => a.name.localeCompare(b.name))
}

function generateParserMap(components: ComponentInfo[]): string {
  const atoms = components.filter(c => c.level === 'atom').map(c => c.name).sort()
  const molecules = components.filter(c => c.level === 'molecule').map(c => c.name).sort()
  const organisms = components.filter(c => c.level === 'organism').map(c => c.name).sort()

  const formatEntries = (names: string[], indent = '  ') => {
    const chunkSize = 4
    const lines: string[] = []
    for (let i = 0; i < names.length; i += chunkSize) {
      const chunk = names.slice(i, i + chunkSize)
      const padding = Math.max(0, 20 - chunk[0].length)
      lines.push(
        `${indent}${chunk.map((n, j) =>
          `"${n}": 'atom'`.padEnd(28)
        ).join(', ')}`,
      )
    }
    return lines.join('\n')
  }

  return `// ─── Component level classification ──────────────────────────────────────────
// Auto-generated by 'nx run catalog' — DO NOT EDIT MANUALLY.
// When adding a new component, place it in the correct tier folder (atoms/
// molecules/ organisms/) and re-run this script.

export const COMPONENT_LEVEL_MAP: Record<string, 'atom' | 'molecule' | 'organism'> = {
  // L1 — Atoms (no component imports)
${formatEntries(atoms)}
  // L2 — Molecules (import L1 atoms only)
${formatEntries(molecules)}
  // L3 — Organisms (import L2 + L1)
${formatEntries(organisms)}
}
`
}

function generateCatalog(components: ComponentInfo[]): string {
  const atoms = components.filter(c => c.level === 'atom').map(c => c.name).sort()
  const molecules = components.filter(c => c.level === 'molecule').map(c => c.name).sort()
  const organisms = components.filter(c => c.level === 'organism').map(c => c.name).sort()

  const formatSection = (title: string, items: string[]): string => {
    if (items.length === 0) return `  ${title}: []`
    const chunked: string[] = []
    for (let i = 0; i < items.length; i += 5) {
      chunked.push(`    '${items.slice(i, i + 5).join("', '")}'`)
    }
    return `  ${title}: [${chunked.join(',\n    ')}]`
  }

  return `// ─── Component Catalog ────────────────────────────────────────────────────────
// Auto-generated by 'nx run catalog' — DO NOT EDIT MANUALLY.
// This is the canonical source of truth for component classification.
// Add a new component to the correct tier folder, then run:
//   npx tsx scripts/catalog.ts

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentCatalog = {
  atoms: ["${atoms.join('", "')}"],
  molecules: ["${molecules.join('", "')}"],
  organisms: ["${organisms.join('", "')}"],
  // Convenience: all components flat
  all: {
    ${atoms.map(n => `  ${n}: 'atom'`).join(',\n    ')}${
      molecules.length > 0 ? ',' : ''
    }${molecules.length > 0 ? '\n    ' : ''}${molecules.map(n => `  ${n}: 'molecule'`).join(',\n    ')}${
      organisms.length > 0 ? ',' : ''
    }${organisms.length > 0 ? '\n    ' : ''}${organisms.map(n => `  ${n}: 'organism'`).join(',\n    ')}
  }
}

// Export typed helpers
export type ComponentLevel = 'atom' | 'molecule' | 'organism'
export function getComponentLevel(name: string): ComponentLevel | undefined {
  return componentCatalog.all[name] as ComponentLevel | undefined
}
} as const
`
}

async function findAndReplaceParserMap(content: string, newMap: string): Promise<string> {
  const startMarker =
    "// ─── Component level classification ──────────────────────────────────────────"
  const endMarker =
    "export function parseComponentTokens"

  const startIdx = content.indexOf(startMarker)
  const endIdx = content.lastIndexOf(endMarker)

  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `Could not find COMPONENT_LEVEL_MAP in parser file. ` +
        `startMarker at ${startIdx}, endMarker at ${endIdx}`,
    )
  }

  const before = content.slice(0, startIdx)
  const after = content.slice(endIdx)
  return before + newMap + '\n\n' + after
}

async function main() {
  console.log('📦 Scanning components directory...\n')

  const components = await scanComponents()

  console.log(`Found ${components.length} components:`)
  console.log(
    `  Atoms: ${components.filter(c => c.level === 'atom').length}`,
  )
  console.log(
    `  Molecules: ${components.filter(c => c.level === 'molecule').length}`,
  )
  console.log(
    `  Organisms: ${components.filter(c => c.level === 'organism').length}\n`,
  )

  // Generate new content
  const newParserMap = generateParserMap(components)
  const newCatalog = generateCatalog(components)

  // Show diff summary
  console.log('📝 Summary of changes:\n')
  console.log('  ✓ COMPONENT_LEVEL_MAP will be updated')
  console.log(`  ✓ Catalog will be updated with ${components.length} entries\n`)

  // Update parser file
  const parserContent = await fs.readFile(PARSER_FILE, 'utf-8')
  const newParserContent = await findAndReplaceParserMap(parserContent, newParserMap)
  await fs.writeFile(PARSER_FILE, newParserContent, 'utf-8')
  console.log(`  ✓ Updated: ${path.relative(ROOT, PARSER_FILE)}`)

  // Update catalog file
  await fs.writeFile(CATALOG_FILE, newCatalog, 'utf-8')
  console.log(`  ✓ Updated: ${path.relative(ROOT, CATALOG_FILE)}\n`)

  console.log('✅ Catalog synced successfully!')
}

main().catch((err) => {
  console.error('❌ Catalog failed:', err.message)
  process.exitCode = 1
})
